apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: hello-agones
spec:
  ports:
    - name: default
      containerPort: 7654
  template:
    spec:
      shareProcessNamespace: true
      containers:
        - name: hello-agones
          image: norman12556/hello-agones
          imagePullPolicy: Never
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
